workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: eyetest
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mni.vision.check.pro
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter clean
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install && cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
